# Generated by Django 5.1.4 on 2025-01-11 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='data_criacao',
        ),
        migrations.AlterField(
            model_name='item',
            name='ano_aquisicao',
            field=models.IntegerField(help_text='Informe o ano da aquisição do item (ex.: 2018)', validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
