# Generated by Django 5.1.4 on 2025-01-16 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_remove_item_data_criacao_alter_item_ano_aquisicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ano_aquisicao',
            field=models.IntegerField(help_text='Informe o ano da aquisição do item (ex.: 2018)'),
        ),
    ]
