# Generated by Django 5.1.4 on 2025-01-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_alter_item_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ano_aquisicao',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='descricao_item',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='marca',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
