# Generated by Django 5.1.4 on 2025-01-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_usuario_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(error_messages={}, max_length=150, unique=True),
        ),
    ]
